spring:
  datasource:
    url: jdbc:yugabytedb://us-west-2.d407c15f-3a83-47da-989e-f4e8f84b885b.aws.ybdb.io:5433/yugabyte?ssl=true&sslmode=allow
    username: ${YUGA_USERNAME}
    password: ${YUGA_PASSWORD}
    driver-class-name: com.yugabyte.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: false

  jpa.properties.javax.persistence.schema-generation:
    create-source: metadata
    scripts.action: create
    scripts.create-target: create.sql

hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  show_sql: true
  hbm2ddl.auto: update

speech-config-properties:
  subscriptionKey: ${SUBSCRIPTION_KEY}
  outputFormat: audio-48khz-192kbitrate-mono-mp3
  serviceUrl: https://eastus.tts.speech.microsoft.com/cognitiveservices/v1
  tokenUrl: https://eastus.api.cognitive.microsoft.com/sts/v1.0/issuetoken

locale-properties:
  neuralVoices:
    usMale:
      voiceName: en-US-GuyNeural
    usFemale:
      voiceName: en-US-JennyNeural
    inMale:
      voiceName: hi-IN-MadhurNeural
    inFemale:
      voiceName: hi-IN-SwaraNeural
    gbMale:
      voiceName: en-GB-AlfieNeural
    gbFemale:
      voiceName: en-GB-OliviaNeural
    frMale:
      voiceName: fr-FR-AlainNeural
    frFemale:
      voiceName: fr-FR-EloiseNeural
    cnMale:
      voiceName: zh-CN-YunyangNeural
    cnFemale:
      voiceName: zh-CN-XiaoyouNeural

logging.level:
  root: INFO

management.endpoints:
    web.exposure.include: mappings, health, info

management.endpoint:
  mappings.enabled: true

management.security.enabled: false