spring:
  datasource:
    url: jdbc:yugabytedb://us-west-2.d407c15f-3a83-47da-989e-f4e8f84b885b.aws.ybdb.io:5433/yugabyte?ssl=true&sslmode=allow
    username: ${YUGA_USERNAME}
    password: ${YUGA_PASSWORD}
    driver-class-name: com.yugabyte.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: false

  jpa.properties.javax.persistence.schema-generation:
    create-source: metadata
    scripts.action: create
    scripts.create-target: create.sql

hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  show_sql: true
  hbm2ddl.auto: update


